#!/bin/bash

mkdir -p dist
rm -r dist/*

cd gh-pages
cp index.html master.json.js ../dist
cd ..

# TODO: Read config from pixie.cson

TITLE="Pixi Paint"
WIDTH=1280
HEIGHT=720
VERSION="0.9.0"

tee dist/package.json <<EOS
{
  "name": "$TITLE",
  "version": "$VERSION",
  "main": "index.html",
  "window": {
    "title": "$TITLE",
    "width": $WIDTH,
    "height": $HEIGHT,
    "toolbar": false
  }
}
EOS

mkdir -p build
rm -r build/*

# Can also build ,linux32,linux64
nwbuild -p "osx,win" dist

# TODO: May be able to only update nw.pack in zip file rather than
# rebuild everything

# Rename nw.exe to "$TITLE".exe
mv build/"$TITLE"/win/nw.exe build/"$TITLE"/win/"$TITLE".exe
# Rename node-webkit.app to "#$TITLE".app
mv build/"$TITLE"/osx/node-webkit.app build/"$TITLE"/osx/"$TITLE".app

# Zip all builds
cd "build/$TITLE"

for folder in *
do
  echo "$folder"
  mkdir -p "$TITLE"
  rm -r "$TITLE"/*
  cp -r "$folder"/* "$TITLE"
  zip -9 -r "../$folder.zip" "$TITLE"
done

# To get nw working on newer linux distros need to modify binary
# cd ~/.nvm/v0.10.28/lib/node_modules/node-webkit-builder/cache/0.9.2/linux32
# sed -i 's/\x75\x64\x65\x76\x2E\x73\x6F\x2E\x30/\x75\x64\x65\x76\x2E\x73\x6F\x2E\x31/g' nw
